// Phonedle - Phone Database
// All phones from 2020+, sourced from GSMArena specs
// Fields: name, manufacturer, chip, screenSize (in), brightness (nits peak),
//         mainCamera (MP), maxCharging (W), releaseYear, releaseQuarter (1-4)

const PHONES = [
  // ─── APPLE ───────────────────────────────────────────────────────────
  {
    name: "iPhone 12",
    manufacturer: "Apple",
    chip: "A14 Bionic",
    screenSize: 6.1,
    brightness: 625,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2020,
    releaseQuarter: 4,
  },
  {
    name: "iPhone 12 mini",
    manufacturer: "Apple",
    chip: "A14 Bionic",
    screenSize: 5.4,
    brightness: 625,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2020,
    releaseQuarter: 4,
  },
  {
    name: "iPhone 12 Pro",
    manufacturer: "Apple",
    chip: "A14 Bionic",
    screenSize: 6.1,
    brightness: 800,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2020,
    releaseQuarter: 4,
  },
  {
    name: "iPhone 12 Pro Max",
    manufacturer: "Apple",
    chip: "A14 Bionic",
    screenSize: 6.7,
    brightness: 800,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2020,
    releaseQuarter: 4,
  },
  {
    name: "iPhone 13",
    manufacturer: "Apple",
    chip: "A15 Bionic",
    screenSize: 6.1,
    brightness: 800,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2021,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 13 mini",
    manufacturer: "Apple",
    chip: "A15 Bionic",
    screenSize: 5.4,
    brightness: 800,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2021,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 13 Pro",
    manufacturer: "Apple",
    chip: "A15 Bionic",
    screenSize: 6.1,
    brightness: 1000,
    mainCamera: 12,
    maxCharging: 27,
    releaseYear: 2021,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 13 Pro Max",
    manufacturer: "Apple",
    chip: "A15 Bionic",
    screenSize: 6.7,
    brightness: 1000,
    mainCamera: 12,
    maxCharging: 27,
    releaseYear: 2021,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 14",
    manufacturer: "Apple",
    chip: "A15 Bionic",
    screenSize: 6.1,
    brightness: 1200,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2022,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 14 Plus",
    manufacturer: "Apple",
    chip: "A15 Bionic",
    screenSize: 6.7,
    brightness: 1200,
    mainCamera: 12,
    maxCharging: 20,
    releaseYear: 2022,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 14 Pro",
    manufacturer: "Apple",
    chip: "A16 Bionic",
    screenSize: 6.1,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 27,
    releaseYear: 2022,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 14 Pro Max",
    manufacturer: "Apple",
    chip: "A16 Bionic",
    screenSize: 6.7,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 27,
    releaseYear: 2022,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 15",
    manufacturer: "Apple",
    chip: "A16 Bionic",
    screenSize: 6.1,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 20,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 15 Plus",
    manufacturer: "Apple",
    chip: "A16 Bionic",
    screenSize: 6.7,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 20,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 15 Pro",
    manufacturer: "Apple",
    chip: "A17 Pro",
    screenSize: 6.1,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 27,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 15 Pro Max",
    manufacturer: "Apple",
    chip: "A17 Pro",
    screenSize: 6.7,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 27,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 16",
    manufacturer: "Apple",
    chip: "A18",
    screenSize: 6.1,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 16 Plus",
    manufacturer: "Apple",
    chip: "A18",
    screenSize: 6.7,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 16 Pro",
    manufacturer: "Apple",
    chip: "A18 Pro",
    screenSize: 6.3,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 27,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 16 Pro Max",
    manufacturer: "Apple",
    chip: "A18 Pro",
    screenSize: 6.9,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 27,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 16e",
    manufacturer: "Apple",
    chip: "A16 Bionic",
    screenSize: 6.1,
    brightness: 1200,
    mainCamera: 48,
    maxCharging: 20,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "iPhone 17",
    manufacturer: "Apple",
    chip: "A19",
    screenSize: 6.1,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 25,
    releaseYear: 2025,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 17 Pro",
    manufacturer: "Apple",
    chip: "A19 Pro",
    screenSize: 6.3,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 30,
    releaseYear: 2025,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 17 Pro Max",
    manufacturer: "Apple",
    chip: "A19 Pro",
    screenSize: 6.9,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 30,
    releaseYear: 2025,
    releaseQuarter: 3,
  },
  {
    name: "iPhone 17 Air",
    manufacturer: "Apple",
    chip: "A19",
    screenSize: 6.6,
    brightness: 2000,
    mainCamera: 48,
    maxCharging: 25,
    releaseYear: 2025,
    releaseQuarter: 3,
  },

  // ─── SAMSUNG ─────────────────────────────────────────────────────────
  {
    name: "Galaxy S21",
    manufacturer: "Samsung",
    chip: "Exynos 2100",
    screenSize: 6.2,
    brightness: 1300,
    mainCamera: 12,
    maxCharging: 25,
    releaseYear: 2021,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S21+",
    manufacturer: "Samsung",
    chip: "Exynos 2100",
    screenSize: 6.7,
    brightness: 1300,
    mainCamera: 12,
    maxCharging: 25,
    releaseYear: 2021,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S21 Ultra",
    manufacturer: "Samsung",
    chip: "Exynos 2100",
    screenSize: 6.8,
    brightness: 1500,
    mainCamera: 108,
    maxCharging: 25,
    releaseYear: 2021,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S22",
    manufacturer: "Samsung",
    chip: "Exynos 2200",
    screenSize: 6.1,
    brightness: 1300,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2022,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S22+",
    manufacturer: "Samsung",
    chip: "Exynos 2200",
    screenSize: 6.6,
    brightness: 1750,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2022,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S22 Ultra",
    manufacturer: "Samsung",
    chip: "Exynos 2200",
    screenSize: 6.8,
    brightness: 1750,
    mainCamera: 108,
    maxCharging: 45,
    releaseYear: 2022,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S23",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.1,
    brightness: 1750,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S23+",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.6,
    brightness: 1750,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S23 Ultra",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.8,
    brightness: 2200,
    mainCamera: 200,
    maxCharging: 45,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S24",
    manufacturer: "Samsung",
    chip: "Exynos 2400",
    screenSize: 6.2,
    brightness: 2600,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S24+",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.7,
    brightness: 2600,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S24 Ultra",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.8,
    brightness: 2600,
    mainCamera: 200,
    maxCharging: 45,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S24 FE",
    manufacturer: "Samsung",
    chip: "Exynos 2500",
    screenSize: 6.7,
    brightness: 1900,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 4,
  },
  {
    name: "Galaxy S25",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.2,
    brightness: 2600,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S25+",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.7,
    brightness: 2600,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S25 Ultra",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.9,
    brightness: 2600,
    mainCamera: 200,
    maxCharging: 45,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy S25 Edge",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.7,
    brightness: 2600,
    mainCamera: 200,
    maxCharging: 25,
    releaseYear: 2025,
    releaseQuarter: 2,
  },
  {
    name: "Galaxy Z Fold 5",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 7.6,
    brightness: 1750,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "Galaxy Z Fold 6",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 7.6,
    brightness: 2600,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "Galaxy Z Flip 5",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.7,
    brightness: 1750,
    mainCamera: 12,
    maxCharging: 25,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "Galaxy Z Flip 6",
    manufacturer: "Samsung",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.7,
    brightness: 2200,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "Galaxy A55",
    manufacturer: "Samsung",
    chip: "Exynos 1480",
    screenSize: 6.6,
    brightness: 1000,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Galaxy A35",
    manufacturer: "Samsung",
    chip: "Exynos 1380",
    screenSize: 6.6,
    brightness: 1000,
    mainCamera: 50,
    maxCharging: 25,
    releaseYear: 2024,
    releaseQuarter: 1,
  },

  // ─── GOOGLE ──────────────────────────────────────────────────────────
  {
    name: "Pixel 5",
    manufacturer: "Google",
    chip: "Snapdragon 765G",
    screenSize: 6.0,
    brightness: 700,
    mainCamera: 12,
    maxCharging: 18,
    releaseYear: 2020,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 6",
    manufacturer: "Google",
    chip: "Google Tensor",
    screenSize: 6.4,
    brightness: 1000,
    mainCamera: 50,
    maxCharging: 30,
    releaseYear: 2021,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 6 Pro",
    manufacturer: "Google",
    chip: "Google Tensor",
    screenSize: 6.7,
    brightness: 1000,
    mainCamera: 50,
    maxCharging: 30,
    releaseYear: 2021,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 7",
    manufacturer: "Google",
    chip: "Google Tensor G2",
    screenSize: 6.3,
    brightness: 1400,
    mainCamera: 50,
    maxCharging: 20,
    releaseYear: 2022,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 7 Pro",
    manufacturer: "Google",
    chip: "Google Tensor G2",
    screenSize: 6.7,
    brightness: 1500,
    mainCamera: 50,
    maxCharging: 23,
    releaseYear: 2022,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 8",
    manufacturer: "Google",
    chip: "Google Tensor G3",
    screenSize: 6.2,
    brightness: 2000,
    mainCamera: 50,
    maxCharging: 27,
    releaseYear: 2023,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 8 Pro",
    manufacturer: "Google",
    chip: "Google Tensor G3",
    screenSize: 6.7,
    brightness: 2400,
    mainCamera: 50,
    maxCharging: 30,
    releaseYear: 2023,
    releaseQuarter: 4,
  },
  {
    name: "Pixel 8a",
    manufacturer: "Google",
    chip: "Google Tensor G3",
    screenSize: 6.1,
    brightness: 2000,
    mainCamera: 64,
    maxCharging: 18,
    releaseYear: 2024,
    releaseQuarter: 2,
  },
  {
    name: "Pixel 9",
    manufacturer: "Google",
    chip: "Google Tensor G4",
    screenSize: 6.3,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 27,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "Pixel 9 Pro",
    manufacturer: "Google",
    chip: "Google Tensor G4",
    screenSize: 6.3,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 37,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "Pixel 9 Pro XL",
    manufacturer: "Google",
    chip: "Google Tensor G4",
    screenSize: 6.8,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 37,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "Pixel 9 Pro Fold",
    manufacturer: "Google",
    chip: "Google Tensor G4",
    screenSize: 8.0,
    brightness: 2700,
    mainCamera: 48,
    maxCharging: 45,
    releaseYear: 2024,
    releaseQuarter: 3,
  },
  {
    name: "Pixel 9a",
    manufacturer: "Google",
    chip: "Google Tensor G4",
    screenSize: 6.3,
    brightness: 2700,
    mainCamera: 48,
    maxCharging: 23,
    releaseYear: 2025,
    releaseQuarter: 2,
  },

  // ─── ONEPLUS ─────────────────────────────────────────────────────────
  {
    name: "OnePlus 9 Pro",
    manufacturer: "OnePlus",
    chip: "Snapdragon 888",
    screenSize: 6.7,
    brightness: 1300,
    mainCamera: 48,
    maxCharging: 65,
    releaseYear: 2021,
    releaseQuarter: 1,
  },
  {
    name: "OnePlus 10 Pro",
    manufacturer: "OnePlus",
    chip: "Snapdragon 8 Gen 1",
    screenSize: 6.7,
    brightness: 1300,
    mainCamera: 48,
    maxCharging: 65,
    releaseYear: 2022,
    releaseQuarter: 1,
  },
  {
    name: "OnePlus 11",
    manufacturer: "OnePlus",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.7,
    brightness: 1300,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "OnePlus 12",
    manufacturer: "OnePlus",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.8,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "OnePlus 13",
    manufacturer: "OnePlus",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.8,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "OnePlus Open",
    manufacturer: "OnePlus",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 7.8,
    brightness: 2800,
    mainCamera: 48,
    maxCharging: 67,
    releaseYear: 2023,
    releaseQuarter: 4,
  },
  {
    name: "OnePlus 13R",
    manufacturer: "OnePlus",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.8,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 80,
    releaseYear: 2025,
    releaseQuarter: 1,
  },

  // ─── XIAOMI ──────────────────────────────────────────────────────────
  {
    name: "Xiaomi 12",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 1",
    screenSize: 6.28,
    brightness: 1100,
    mainCamera: 50,
    maxCharging: 67,
    releaseYear: 2022,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 12 Pro",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 1",
    screenSize: 6.73,
    brightness: 1500,
    mainCamera: 50,
    maxCharging: 120,
    releaseYear: 2022,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 13",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.36,
    brightness: 1900,
    mainCamera: 50,
    maxCharging: 67,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 13 Pro",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.73,
    brightness: 1900,
    mainCamera: 50,
    maxCharging: 120,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 14",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.36,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 90,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 14 Pro",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.73,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 120,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 14 Ultra",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.73,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 90,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Xiaomi 15",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.36,
    brightness: 3200,
    mainCamera: 50,
    maxCharging: 90,
    releaseYear: 2024,
    releaseQuarter: 4,
  },
  {
    name: "Xiaomi 15 Pro",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.73,
    brightness: 3200,
    mainCamera: 50,
    maxCharging: 90,
    releaseYear: 2024,
    releaseQuarter: 4,
  },
  {
    name: "Xiaomi 15 Ultra",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.73,
    brightness: 3200,
    mainCamera: 200,
    maxCharging: 90,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "Redmi Note 13 Pro+",
    manufacturer: "Xiaomi",
    chip: "Dimensity 7200 Ultra",
    screenSize: 6.67,
    brightness: 1800,
    mainCamera: 200,
    maxCharging: 120,
    releaseYear: 2023,
    releaseQuarter: 4,
  },
  {
    name: "Redmi Note 14 Pro+",
    manufacturer: "Xiaomi",
    chip: "Snapdragon 7s Gen 3",
    screenSize: 6.67,
    brightness: 3000,
    mainCamera: 200,
    maxCharging: 90,
    releaseYear: 2024,
    releaseQuarter: 4,
  },

  // ─── SONY ────────────────────────────────────────────────────────────
  {
    name: "Xperia 1 III",
    manufacturer: "Sony",
    chip: "Snapdragon 888",
    screenSize: 6.5,
    brightness: 900,
    mainCamera: 12,
    maxCharging: 30,
    releaseYear: 2021,
    releaseQuarter: 2,
  },
  {
    name: "Xperia 1 IV",
    manufacturer: "Sony",
    chip: "Snapdragon 8 Gen 1",
    screenSize: 6.5,
    brightness: 900,
    mainCamera: 12,
    maxCharging: 30,
    releaseYear: 2022,
    releaseQuarter: 2,
  },
  {
    name: "Xperia 1 V",
    manufacturer: "Sony",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.5,
    brightness: 900,
    mainCamera: 52,
    maxCharging: 30,
    releaseYear: 2023,
    releaseQuarter: 2,
  },
  {
    name: "Xperia 1 VI",
    manufacturer: "Sony",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.5,
    brightness: 1500,
    mainCamera: 52,
    maxCharging: 30,
    releaseYear: 2024,
    releaseQuarter: 2,
  },
  {
    name: "Xperia 5 V",
    manufacturer: "Sony",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.1,
    brightness: 900,
    mainCamera: 52,
    maxCharging: 30,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "Xperia 10 VI",
    manufacturer: "Sony",
    chip: "Snapdragon 6 Gen 1",
    screenSize: 6.1,
    brightness: 900,
    mainCamera: 48,
    maxCharging: 30,
    releaseYear: 2024,
    releaseQuarter: 2,
  },

  // ─── MOTOROLA ────────────────────────────────────────────────────────
  {
    name: "Motorola Edge 40 Pro",
    manufacturer: "Motorola",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.7,
    brightness: 1600,
    mainCamera: 50,
    maxCharging: 125,
    releaseYear: 2023,
    releaseQuarter: 2,
  },
  {
    name: "Motorola Edge 50 Pro",
    manufacturer: "Motorola",
    chip: "Snapdragon 7 Gen 3",
    screenSize: 6.7,
    brightness: 2000,
    mainCamera: 50,
    maxCharging: 125,
    releaseYear: 2024,
    releaseQuarter: 2,
  },
  {
    name: "Motorola Edge 50 Ultra",
    manufacturer: "Motorola",
    chip: "Snapdragon 8s Gen 3",
    screenSize: 6.7,
    brightness: 2500,
    mainCamera: 50,
    maxCharging: 125,
    releaseYear: 2024,
    releaseQuarter: 2,
  },
  {
    name: "Motorola Razr 50 Ultra",
    manufacturer: "Motorola",
    chip: "Snapdragon 8s Gen 3",
    screenSize: 6.9,
    brightness: 2400,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2024,
    releaseQuarter: 2,
  },
  {
    name: "Motorola Edge 60 Pro",
    manufacturer: "Motorola",
    chip: "Dimensity 8350",
    screenSize: 6.7,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 68,
    releaseYear: 2025,
    releaseQuarter: 1,
  },

  // ─── NOTHING ─────────────────────────────────────────────────────────
  {
    name: "Nothing Phone (2)",
    manufacturer: "Nothing",
    chip: "Snapdragon 8+ Gen 1",
    screenSize: 6.7,
    brightness: 1600,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2023,
    releaseQuarter: 3,
  },
  {
    name: "Nothing Phone (2a)",
    manufacturer: "Nothing",
    chip: "Dimensity 7200 Pro",
    screenSize: 6.7,
    brightness: 1300,
    mainCamera: 50,
    maxCharging: 45,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Nothing Phone (3a)",
    manufacturer: "Nothing",
    chip: "Snapdragon 7s Gen 3",
    screenSize: 6.77,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 50,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "Nothing Phone (3)",
    manufacturer: "Nothing",
    chip: "Snapdragon 8s Elite",
    screenSize: 6.77,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 65,
    releaseYear: 2025,
    releaseQuarter: 3,
  },

  // ─── OPPO ────────────────────────────────────────────────────────────
  {
    name: "OPPO Find X6 Pro",
    manufacturer: "OPPO",
    chip: "Snapdragon 8 Gen 2",
    screenSize: 6.82,
    brightness: 2500,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2023,
    releaseQuarter: 1,
  },
  {
    name: "OPPO Find X7 Ultra",
    manufacturer: "OPPO",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.82,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "OPPO Reno 12 Pro",
    manufacturer: "OPPO",
    chip: "Dimensity 9200+",
    screenSize: 6.7,
    brightness: 1600,
    mainCamera: 50,
    maxCharging: 80,
    releaseYear: 2024,
    releaseQuarter: 2,
  },
  {
    name: "OPPO Find N3 Flip",
    manufacturer: "OPPO",
    chip: "Dimensity 9200",
    screenSize: 6.8,
    brightness: 2800,
    mainCamera: 50,
    maxCharging: 44,
    releaseYear: 2023,
    releaseQuarter: 4,
  },

  // ─── VIVO / IQOO ──────────────────────────────────────────────────────
  {
    name: "vivo X100 Pro",
    manufacturer: "vivo",
    chip: "Dimensity 9300",
    screenSize: 6.78,
    brightness: 3000,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2023,
    releaseQuarter: 4,
  },
  {
    name: "vivo X200 Pro",
    manufacturer: "vivo",
    chip: "Dimensity 9400",
    screenSize: 6.78,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 90,
    releaseYear: 2024,
    releaseQuarter: 4,
  },
  {
    name: "iQOO 13",
    manufacturer: "vivo",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.82,
    brightness: 4500,
    mainCamera: 50,
    maxCharging: 120,
    releaseYear: 2024,
    releaseQuarter: 4,
  },

  // ─── HONOR ───────────────────────────────────────────────────────────
  {
    name: "Honor Magic6 Pro",
    manufacturer: "Honor",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.8,
    brightness: 5000,
    mainCamera: 50,
    maxCharging: 80,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "Honor Magic7 Pro",
    manufacturer: "Honor",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.8,
    brightness: 5000,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2025,
    releaseQuarter: 1,
  },
  {
    name: "Honor 200 Pro",
    manufacturer: "Honor",
    chip: "Snapdragon 8s Gen 3",
    screenSize: 6.78,
    brightness: 4000,
    mainCamera: 50,
    maxCharging: 100,
    releaseYear: 2024,
    releaseQuarter: 2,
  },

  // ─── ASUS ─────────────────────────────────────────────────────────────
  {
    name: "ASUS ROG Phone 8 Pro",
    manufacturer: "ASUS",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.78,
    brightness: 2500,
    mainCamera: 50,
    maxCharging: 65,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "ASUS Zenfone 11 Ultra",
    manufacturer: "ASUS",
    chip: "Snapdragon 8 Gen 3",
    screenSize: 6.78,
    brightness: 2500,
    mainCamera: 50,
    maxCharging: 65,
    releaseYear: 2024,
    releaseQuarter: 1,
  },
  {
    name: "ASUS ROG Phone 9 Pro",
    manufacturer: "ASUS",
    chip: "Snapdragon 8 Elite",
    screenSize: 6.78,
    brightness: 2500,
    mainCamera: 50,
    maxCharging: 65,
    releaseYear: 2024,
    releaseQuarter: 4,
  },
];

// Helper: get unique sorted values for a field
function getUniqueValues(field) {
  return [...new Set(PHONES.map((p) => p[field]))].sort();
}

// Seed-based random (for daily mode)
function seededRandom(seed) {
  let s = seed;
  return function () {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return (s >>> 0) / 0x100000000;
  };
}

function getDailySeed() {
  const now = new Date();
  const dateStr = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}`;
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = ((hash << 5) - hash + dateStr.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
}

function getDailyPhone() {
  const seed = getDailySeed();
  const rng = seededRandom(seed);
  const idx = Math.floor(rng() * PHONES.length);
  return PHONES[idx];
}

function getRandomPhone() {
  return PHONES[Math.floor(Math.random() * PHONES.length)];
}

// Categories config
// Tolerances: green = exact (or within tolerance), orange = close but not exact
// Camera: exact MP only (48 ≠ 50), Screen: ±0.05" counts as same, Brightness/Charging: exact only
const CATEGORIES = [
  { key: "manufacturer", label: "Manufacturer", type: "exact" },
  { key: "chip", label: "Chip / CPU", type: "exact" },
  { key: "screenSize", label: "Screen Size", type: "numeric", unit: '"', tolerance: 0.05, closeTolerance: 0.4 },
  { key: "brightness", label: "Peak Brightness", type: "numeric", unit: " nits", tolerance: 1, closeTolerance: 600 },
  { key: "mainCamera", label: "Main Camera", type: "numeric", unit: " MP", tolerance: 0, closeTolerance: 18 },
  { key: "maxCharging", label: "Max Charging", type: "numeric", unit: "W", tolerance: 1, closeTolerance: 22 },
  { key: "releaseYear", label: "Release", type: "date" },
];

// Compare a guess to the target for a category
// Returns: { result: 'correct'|'close'|'wrong', direction: 'up'|'down'|null, displayValue: string }
function compareField(guess, target, category) {
  const gVal = guess[category.key];
  const tVal = target[category.key];

  if (category.type === "exact") {
    return {
      result: gVal === tVal ? "correct" : "wrong",
      direction: null,
      displayValue: gVal,
    };
  }

  if (category.type === "numeric") {
    const diff = Math.abs(gVal - tVal);
    const direction = gVal < tVal ? "up" : gVal > tVal ? "down" : null;
    let result = "wrong";
    if (diff <= category.tolerance) result = "correct";
    else if (diff <= category.closeTolerance) result = "close";
    return {
      result,
      direction: result === "correct" ? null : direction,
      displayValue: category.key === "screenSize" ? gVal.toFixed(1) + category.unit : gVal + category.unit,
    };
  }

  if (category.type === "date") {
    const gYear = guess.releaseYear;
    const gQ = guess.releaseQuarter;
    const tYear = target.releaseYear;
    const tQ = target.releaseQuarter;

    const gTotal = gYear * 4 + gQ;
    const tTotal = tYear * 4 + tQ;
    const diff = Math.abs(gTotal - tTotal);
    const direction = gTotal < tTotal ? "up" : gTotal > tTotal ? "down" : null;

    let result = "wrong";
    if (diff === 0) result = "correct";
    else if (diff <= 2 || gYear === tYear) result = "close";

    return {
      result,
      direction: result === "correct" ? null : direction,
      displayValue: `${gYear} Q${gQ}`,
    };
  }
}

// Evaluate all categories for a guess
function evaluateGuess(guess, target) {
  return CATEGORIES.map((cat) => ({
    ...cat,
    ...compareField(guess, target, cat),
  }));
}

// Pick a random hint category index
function getRandomHintCategory(seed) {
  const rng = seededRandom(seed + 999);
  return Math.floor(rng() * CATEGORIES.length);
}
